# Generated by Django 6.0.3 on 2026-03-31 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('civility', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('verdict_date', models.DateField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_cases', to='transparence.party')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_cases', to='transparence.politician')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('publisher', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('published_at', models.DateField()),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='transparence.legalcase')),
            ],
        ),
    ]
