# Generated by Django 6.0.3 on 2026-04-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparence", "0003_apiclient_refreshtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="politician",
            name="civility",
        ),
        migrations.RemoveField(
            model_name="politician",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="politician",
            name="last_name",
        ),
        migrations.AddField(
            model_name="legalcase",
            name="external_updated_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="politician",
            name="full_name",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="politician",
            name="external_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
