# Generated by Django 6.0.3 on 2026-04-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparence", "0004_remove_politician_civility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="politician",
            name="full_name",
            field=models.CharField(max_length=250),
        ),
    ]
