# Generated by Django 6.0.3 on 2026-04-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparence", "0005_alter_politician_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalcase",
            name="verdict_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
