# Generated by Django 6.0.3 on 2026-04-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparence", "0006_alter_legalcase_verdict_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalcase",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
