# Generated by Django 6.0.3 on 2026-04-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparence", "0007_alter_legalcase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalcase",
            name="external_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
