# Generated by Django 6.0.3 on 2026-04-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transparence", "0008_alter_legalcase_external_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="external_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
