# Generated by Django 6.0.3 on 2026-04-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transparence", "0009_alter_source_external_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="description",
        ),
    ]
