# Generated by Django 6.0.3 on 2026-04-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transparence", "0010_remove_source_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refreshtoken",
            name="client",
        ),
        migrations.DeleteModel(
            name="ApiClient",
        ),
        migrations.DeleteModel(
            name="RefreshToken",
        ),
    ]
