# Generated by Django 6.0.3 on 2026-04-08 13:59
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("transparence", "0011_remove_refreshtoken_client_delete_apiclient_and_more"),
    ]

    operations = [
        TrigramExtension(),
    ]
